export const ALL_MCQ_REQUEST = "ALL_MCQ_REQUEST";
export const ALL_MCQ_SUCCESS = "ALL_MCQ_SUCCESS";
export const ALL_MCQ_FAILURE = "ALL_MCQ_FAILURE";

export const GET_RESULT_REQUEST = "GET_RESULT_REQUEST";
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS";
export const GET_RESULT_FAILURE = "GET_RESULT_FAILURE";


export const CLEAR_ERROR = "CLEAR_ERROR";