export const LOGIN_SUCCESS_REQUEST = "LOGIN_SUCCESS_REQUEST";
export const LOGIN_SUCCESS_SUCCESS = "LOGIN_SUCCESS_SUCCESS";
export const LOGIN_SUCCESS_FAILURE = "LOGIN_SUCCESS_FAILURE";

export const REGISTER_SUCCESS_REQUEST = "REGISTER_SUCCESS_REQUEST";
export const REGISTER_SUCCESS_SUCCESS = "REGISTER_SUCCESS_SUCCESS";
export const REGISTER_SUCCESS_FAILURE = "REGISTER_SUCCESS_FAILURE";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";


export const CLEAR_ERROR = "CLEAR_ERROR";