export const CREATE_MCQ_REQUEST = "CREATE_MCQ_REQUEST";
export const CREATE_MCQ_SUCCESS = "CREATE_MCQ_SUCCESS";
export const CREATE_MCQ_FAILURE = "CREATE_MCQ_FAILURE";


export const UPDATE_MCQ_REQUEST = "UPDATE_MCQ_REQUEST";
export const UPDATE_MCQ_SUCCESS = "UPDATE_MCQ_SUCCESS";
export const UPDATE_MCQ_FAILURE = "UPDATE_MCQ_FAILURE";


export const DELETE_MCQ_REQUEST = "DELETE_MCQ_REQUEST";
export const DELETE_MCQ_SUCCESS = "DELETE_MCQ_SUCCESS";
export const DELETE_MCQ_FAILURE = "DELETE_MCQ_FAILURE";


export const GET_ALL_MCQ_REQUEST = "GET_ALL_MCQ_REQUEST";
export const GET_ALL_MCQ_SUCCESS = "GET_ALL_MCQ_SUCCESS";
export const GET_ALL_MCQ_FAILURE = "GET_ALL_MCQ_FAILURE";

export const CLEAR_ERROR = "CLEAR_ERROR";